package com.illusionbox.offerme.model;
// Generated 21-Sep-2015 19:17:54 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private String email;
     private String password;
     private String name;
     private Set<RestaurantManager> restaurantManagers = new HashSet<RestaurantManager>(0);

    public Administrator() {
    }

	
    public Administrator(String email) {
        this.email = email;
    }
    public Administrator(String email, String password, String name, Set<RestaurantManager> restaurantManagers) {
       this.email = email;
       this.password = password;
       this.name = name;
       this.restaurantManagers = restaurantManagers;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<RestaurantManager> getRestaurantManagers() {
        return this.restaurantManagers;
    }
    
    public void setRestaurantManagers(Set<RestaurantManager> restaurantManagers) {
        this.restaurantManagers = restaurantManagers;
    }




}


