package com.illusionbox.offerme.model;
// Generated 21-Sep-2015 02:18:11 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private String email;
     private String accessToken;
     private String name;
     private String tel;
     private String facebook;
     private Integer offerCount;
     private Boolean subscribe;
     private Set<Offer> offers = new HashSet<Offer>(0);

    public Customer() {
    }

	
    public Customer(String email) {
        this.email = email;
    }
    public Customer(String email, String accessToken, String name, String tel, String facebook, Integer offerCount, Boolean subscribe, Set<Offer> offers) {
       this.email = email;
       this.accessToken = accessToken;
       this.name = name;
       this.tel = tel;
       this.facebook = facebook;
       this.offerCount = offerCount;
       this.subscribe = subscribe;
       this.offers = offers;
    }
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getAccessToken() {
        return this.accessToken;
    }
    
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public Integer getOfferCount() {
        return this.offerCount;
    }
    
    public void setOfferCount(Integer offerCount) {
        this.offerCount = offerCount;
    }
    public Boolean getSubscribe() {
        return this.subscribe;
    }
    
    public void setSubscribe(Boolean subscribe) {
        this.subscribe = subscribe;
    }
    public Set<Offer> getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }




}


