package com.illusionbox.offerme.model;
// Generated 21-Sep-2015 02:18:11 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private Integer idrestaurant;
     private RestaurantManager restaurantManager;
     private String location;
     private String address;
     private String tel;
     private String web;
     private String logoUrl;
     private String bannerUrl;
     private String openingHrs;
     private String description;
     private Float rating;
     private String state;
     private Set<Offer> offers = new HashSet<Offer>(0);

    public Restaurant() {
    }

	
    public Restaurant(RestaurantManager restaurantManager) {
        this.restaurantManager = restaurantManager;
    }
    public Restaurant(RestaurantManager restaurantManager, String location, String address, String tel, String web, String logoUrl, String bannerUrl, String openingHrs, String description, Float rating, String state, Set<Offer> offers) {
       this.restaurantManager = restaurantManager;
       this.location = location;
       this.address = address;
       this.tel = tel;
       this.web = web;
       this.logoUrl = logoUrl;
       this.bannerUrl = bannerUrl;
       this.openingHrs = openingHrs;
       this.description = description;
       this.rating = rating;
       this.state = state;
       this.offers = offers;
    }
   
    public Integer getIdrestaurant() {
        return this.idrestaurant;
    }
    
    public void setIdrestaurant(Integer idrestaurant) {
        this.idrestaurant = idrestaurant;
    }
    public RestaurantManager getRestaurantManager() {
        return this.restaurantManager;
    }
    
    public void setRestaurantManager(RestaurantManager restaurantManager) {
        this.restaurantManager = restaurantManager;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public String getBannerUrl() {
        return this.bannerUrl;
    }
    
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }
    public String getOpeningHrs() {
        return this.openingHrs;
    }
    
    public void setOpeningHrs(String openingHrs) {
        this.openingHrs = openingHrs;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Float getRating() {
        return this.rating;
    }
    
    public void setRating(Float rating) {
        this.rating = rating;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set<Offer> getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }




}


