package com.illusionbox.offerme.model;
// Generated 21-Sep-2015 19:17:54 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Restaurant generated by hbm2java
 */
public class Restaurant  implements java.io.Serializable {


     private Integer idrestaurant;
     private RestaurantManager restaurantManager;
     private String name;
     private double latitude;
     private double longitude;
     private String address;
     private String tel;
     private String web;
     private String logoUrl;
     private String bannerUrl;
     private String openingHrs;
     private String description;
     private Float rating;
     private String state;
     private String type;
     private Set<Offer> offers = new HashSet<Offer>(0);

    public Restaurant() {
    }

	
    public Restaurant(RestaurantManager restaurantManager, String name, double latitude, double longitude) {
        this.restaurantManager = restaurantManager;
        this.name = name;
        this.latitude = latitude;
        this.longitude = longitude;
    }
    public Restaurant(RestaurantManager restaurantManager, String name, double latitude, double longitude, String address, String tel, String web, String logoUrl, String bannerUrl, String openingHrs, String description, Float rating, String state, String type, Set<Offer> offers) {
       this.restaurantManager = restaurantManager;
       this.name = name;
       this.latitude = latitude;
       this.longitude = longitude;
       this.address = address;
       this.tel = tel;
       this.web = web;
       this.logoUrl = logoUrl;
       this.bannerUrl = bannerUrl;
       this.openingHrs = openingHrs;
       this.description = description;
       this.rating = rating;
       this.state = state;
       this.type = type;
       this.offers = offers;
    }
   
    public Integer getIdrestaurant() {
        return this.idrestaurant;
    }
    
    public void setIdrestaurant(Integer idrestaurant) {
        this.idrestaurant = idrestaurant;
    }
    public RestaurantManager getRestaurantManager() {
        return this.restaurantManager;
    }
    
    public void setRestaurantManager(RestaurantManager restaurantManager) {
        this.restaurantManager = restaurantManager;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public String getLogoUrl() {
        return this.logoUrl;
    }
    
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }
    public String getBannerUrl() {
        return this.bannerUrl;
    }
    
    public void setBannerUrl(String bannerUrl) {
        this.bannerUrl = bannerUrl;
    }
    public String getOpeningHrs() {
        return this.openingHrs;
    }
    
    public void setOpeningHrs(String openingHrs) {
        this.openingHrs = openingHrs;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Float getRating() {
        return this.rating;
    }
    
    public void setRating(Float rating) {
        this.rating = rating;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Offer> getOffers() {
        return this.offers;
    }
    
    public void setOffers(Set<Offer> offers) {
        this.offers = offers;
    }




}


